[package]
name = "rustssi"
version = "0.1.0"
edition = "2021"

[dependencies]
libbpf-rs = "0.24"
libc = "0.2"
anyhow = "1"
smoltcp = { version = "0.12", default-features = false, features = [
    "std",
    "medium-ip",
    "proto-ipv4",
    "socket-tcp",
] }

[build-dependencies]
libbpf-cargo = "0.24"
